@startuml C4_Elements_L3
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title C4 Component Diagram (L3) - Wireshark

Container_Boundary(wiresharkBoundary, "Wireshark App") {
    Component(gui, "GUI", "Component: C++/Qt", "Graphical Interface for user interaction, displaying captured data and configuring captures")
    Component(core, "Core", "Component: C", "Orchestrates the other blocks, coordinates the capture process")
    Component(capture, "Capture", "Component: C", "The interface to the capture engine. Manages capture sessions")
    Component(epan, "Epan (Enhanced Packet ANalyzer)", "Component: C", "The packet analalyzing engine. Dissects and analyzes packets")
    Component(wireTap, "Wiretap", "Component: C", "Reads and writes capture files in more than 20 file formats (.pcap, .cap, etc.)")
}

Container_Ext(dumpcap, "Dumpcap", "Container: C", "The capture engine itself, executed with elevated privileges.")
SystemDb_Ext(filesystem, "File System", "Stores temporary and saved .pcapng files")

Rel(gui, core, "Sends commands to and receives updates from", "Signals & Slots")
Rel(core, capture, "Delegates capture management to", "Function calling")
Rel(core, epan, "Requests packet dissection from", "Function calling")

Rel(capture, dumpcap, "Launches and communicates with", "IPC Sync Pipe")
' Capture initializes dumpcap. The core communicates with Dumpcap thanks to Capture
Rel(dumpcap, filesystem, "Writes raw packets to", "File I/O")
' Dumpcap writes raw packets in a temporary file on the hard disk.
' Once a packets block has been written, Dumpcap signals Capture, which in turn signals the Core

Rel(core, wireTap, "Calls API to receive files read by", "Function calling")
' Once the Core receives the signal, it uses Wiretap to read the packets

Rel(wireTap, filesystem, "Reads packets from and writes packets to", "File I/O")
' Wiretap reads the packets from the hard disk

' CONNECTION BETWEEN WIRETAP AND CAPTURE IS ONLY FOR SHARED DATA STRUCTURES AND FILE FORMATS, NOT FOR FUNCTION CALLS.
' UTILITIES ARE EXCLUDED SINCE THEY ARE NOT COMPONENTS, BUT RATHER HELPER CLASSES AND FUNCTIONS USED BY THE COMPONENTS.

SHOW_LEGEND()
@enduml