@startuml C4_Elements_L2
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Container Diagram (L2) - Wireshark

Person(wiresharkUser, "User", "A person who wants to analyze network traffic")

' Sistemi esterni identici al livello 1
System_Ext(npcap, "npcap", "Captures raw packets on Windows systems")
System_Ext(libpcap, "libpcap", "Captures raw packets on Unix-like systems")

' Confine del sistema Wireshark
System_Boundary(wiresharkBoundary, "Wireshark System") {
    
    Container(wiresharkApp, "Wireshark App", "Container: C, C++, Qt", "GUI application. Orchestrates the capture, reads files, decodes protocols and displays data.")
    
    Container(dumpcap, "Dumpcap", "Container: C", "Privileged executable. Intercepts network traffic and saves raw packets directly to disk.")

    ContainerDb(filesystem, "File System", "Container: Local OS File System", "Stores temporary and saved .pcapng files")
}

' Relazioni Utente
Rel(wiresharkUser, wiresharkApp, "Consults packets and configures capture")

' Relazioni interne (IPC)
Rel(wiresharkApp, dumpcap, "Controls and monitors status", "IPC Sync Pipe")

' Relazioni con i Sistemi Esterni
Rel(npcap, dumpcap, "Provides raw packets", "Windows calls")
Rel(libpcap, dumpcap, "Provides raw packets", "Unix calls")

Rel(dumpcap, filesystem, "Writes raw packets to", "File I/O")
Rel(wiresharkApp, filesystem, "Reads packets from and writes packets to", "File I/O")

SHOW_LEGEND()
@enduml