@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(wiresharkUser, "User", "A person who wants to analyze network traffic")

Boundary(wiresharkBoundary, "Wireshark", "Wireshark Foundation") {
    System(wireshark, "Wireshark", "Optional Description")
    System_Ext(Dumpcap, "Dumpcap", "Memorizes packets on disk")
}

System_Ext(npcap, "npcap", "Captures raw packets on windows systems")

System_Ext(libpcap, "libpcap", "Captures raw packets on unix-like systems")

System_Ext(filesystem, "filesystem", "Stores captured packets in .pcapng format")

Rel(wiresharkUser, wireshark, "Consults packets")


Rel(npcap, Dumpcap, "Consults packets")

Rel(libpcap, Dumpcap, "Consults packets")

Rel(Dumpcap, wireshark, "Provides packets")

Rel(filesystem, wireshark, "Provides packets")

Rel(Dumpcap, filesystem, "Stores packets")

SHOW_LEGEND()

@endumlx